typography_spectrum: 0.45323054445907474
color:
  brandColors:
    - '#1A1F2B'
    - '#30395C'
    - '#4A6491'
    - '#85A5CC'
    - '#D0E4F2'
  brandStrength: 0.7446833795402199
  lightness: 0.6092136492952704
  saturation: 0.20985064911656082
  rhythmicContrast: 0.5623855956364423
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9095723556820303
analytics:
  google: null
  facebook: null
  twitter: null
name: Cabo Pulmo
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Cabo Pulmo National Marine Park
description: Los Frailes Bay
purpose: []
